# Project 1: Transactions – Pass 08

## Problem Definition

#### 1. State the business problem.

Translate the business problem into a Data Science problem by stating what kind of problem it is ( supervised vs unsupervised ) and whether it is a classification, regression, or clustering problem.  Mention which model will be used, if known.

> We want to predict whether or not a future customer will complete a transaction (e.g., a product purchase, loan or bill payment, or subscription retention) based on prior transaction data. Such predictions can help determine higher-risk customers and present incentives to drive future transaction completions and increase sales.

> This is a supervised, categorical binary classification problem, where the target data is whether a customer transaction was successful (true or false). To achieve this, it uses a Gaussian Naive Bayes model to make predictions about transaction success.

## Data Collection

#### 2. Load Pandas, Numpy, and Matplotlib modules

In [16]:
# imports
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets, metrics
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split

#### 3. Load data Train.csv from AWS S3.

In [17]:
# url
url = 'https://ddc-datascience.s3.amazonaws.com/Projects/Project.1-Transactions/Data/Transaction.train.big.csv'

- Set number of columns and rows for this pass:

In [18]:
# set cols and rows for pass
num_cols = 50
num_rows = 50_000

num_cols, num_rows

(50, 50000)

- Read in the data from .csv using pandas:

In [19]:
# make dataframe
df = pd.read_csv(
    url,
    usecols=range(num_cols),
    nrows=num_rows,
)

- Check the dataframe:

In [20]:
# check dataframe
df

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45,var_46
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,3.4635,17.2850,16.5520,NaN,-6.8709,NaN,NaN,NaN,NaN,NaN
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,49995,train_49995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,49996,train_49996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,49997,train_49997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,49998,train_49998,0.0,7.7807,11.4038,11.2746,NaN,7.6426,NaN,NaN,...,5.0832,18.0498,19.0913,NaN,-0.0056,NaN,NaN,NaN,NaN,NaN
49999,49999,train_49999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Cleaning

#### 4. Examine the data using tools we have used in class. You should be identifying the various columns such as ...

    - target column
    - feature columns
    - identifier columns
    - null columns
    - null rows

    Tools you should be using include, but are not limited to:

    - head
    - tail
    - shape
    - size
    - info
    - describe
    - nunique
    - unique
    - isnull/isna

In [21]:
# define target_col
target_col = 'target'
target_col

'target'

- head

In [22]:
# head
df.head()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45,var_46
0,0,train_0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,train_1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,train_2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,train_3,0.0,4.6739,22.3915,15.6015,NaN,0.0464,NaN,NaN,...,3.4635,17.285,16.552,NaN,-6.8709,NaN,NaN,NaN,NaN,NaN
4,4,train_4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- tail

In [23]:
# tail
df.tail()

,Unnamed: 0,ID_code,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,...,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45,var_46
49995,49995,train_49995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49996,49996,train_49996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49997,49997,train_49997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49998,49998,train_49998,0.0,7.7807,11.4038,11.2746,NaN,7.6426,NaN,NaN,...,5.0832,18.0498,19.0913,NaN,-0.0056,NaN,NaN,NaN,NaN,NaN
49999,49999,train_49999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- shape

In [24]:
# shape
df.shape

(50000, 50)

- size

In [25]:
# size
df.size

2500000

- info

In [26]:
# info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 50 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  50000 non-null  int64
 1   ID_code     50000 non-null  object
 2   target      8506 non-null   float64
 3   var_0       8506 non-null   float64
 4   var_1       8506 non-null   float64
 5   var_2       8506 non-null   float64
 6   var_3       0 non-null      float64
 7   var_4       8506 non-null   float64
 8   var_5       0 non-null      float64
 9   var_6       0 non-null      float64
 10  var_7       8506 non-null   float64
 11  var_8       8506 non-null   float64
 12  var_9       0 non-null      float64
 13  var_10      0 non-null      float64
 14  var_11      0 non-null      float64
 15  var_12      0 non-null      float64
 16  var_13      0 non-null      float64
 17  var_14      8506 non-null   float64
 18  var_15      8506 non-null   float64
 19  var_16      0 non-null      float64
 20  var_17      8506 non-null   float64
 21  var_18      0 non-null      float64
 22  var_19      0 non-null      float64
 23  var_20      8506 non-null   float64
 24  var_21      8506 non-null   float64
 25  var_22      8506 non-null   float64
 26  var_23      0 non-null      float64
 27  var_24      8506 non-null   float64
 28  var_25      0 non-null      float64
 29  var_26      8506 non-null   float64
 30  var_27      8506 non-null   float64
 31  var_28      8506 non-null   float64
 32  var_29      8506 non-null   float64
 33  var_30      0 non-null      float64
 34  var_31      0 non-null      float64
 35  var_32      0 non-null      float64
 36  var_33      0 non-null      float64
 37  var_34      0 non-null      float64
 38  var_35      0 non-null      float64
 39  var_36      8506 non-null   float64
 40  var_37      8506 non-null   float64
 41  var_38      8506 non-null   float64
 42  var_39      8506 non-null   float64
 43  var_40      0 non-null      float64
 44  var_41      8506 non-null   float64
 45  var_42      0 non-null      float64
 46  var_43      0 non-null      float64
 47  var_44      0 non-null      float64
 48  var_45      0 non-null      float64
 49  var_46      0 non-null      float64
dtypes: float64(48), int64(1), object(1)
memory usage: 19.1+ MB

- describe

In [27]:
# describe
df.describe()

,Unnamed: 0,target,var_0,var_1,var_2,var_3,var_4,var_5,var_6,var_7,...,var_37,var_38,var_39,var_40,var_41,var_42,var_43,var_44,var_45,var_46
count,50000.000000,8506.000000,8506.000000,8506.000000,8506.000000,0.0,8506.000000,0.0,0.0,8506.000000,...,8506.000000,8506.000000,8506.000000,0.0,8506.000000,0.0,0.0,0.0,0.0,0.0
mean,24999.500000,0.098754,7.433406,15.873152,12.743673,NaN,-0.666477,NaN,NaN,1.216609,...,3.335911,19.317877,18.439225,NaN,5.768740,NaN,NaN,NaN,NaN,NaN
std,14433.901067,0.298349,2.998493,3.026206,4.167618,NaN,5.989788,NaN,NaN,5.206295,...,4.541526,5.013834,4.398037,NaN,7.462482,NaN,NaN,NaN,NaN,NaN
min,0.000000,0.000000,-0.482300,7.193400,1.263600,NaN,-20.962200,NaN,NaN,-12.739600,...,-13.999500,5.133100,6.673300,NaN,-15.121100,NaN,NaN,NaN,NaN,NaN
25%,12499.750000,0.000000,5.192575,13.822750,9.709300,NaN,-4.915275,NaN,NaN,-2.600700,...,0.018500,15.712475,15.044250,NaN,0.638225,NaN,NaN,NaN,NaN,NaN
50%,24999.500000,0.000000,7.286950,15.971650,12.660600,NaN,-0.585350,NaN,NaN,1.209900,...,3.366600,19.318800,18.293700,NaN,5.958900,NaN,NaN,NaN,NaN,NaN
75%,37499.250000,0.000000,9.523925,18.092725,15.755275,NaN,3.615725,NaN,NaN,5.146000,...,6.482825,22.906000,21.907575,NaN,11.427175,NaN,NaN,NaN,NaN,NaN
max,49999.000000,1.000000,16.716500,24.508500,25.848100,NaN,15.973100,NaN,NaN,18.419700,...,17.686100,33.940300,31.018900,NaN,26.401100,NaN,NaN,NaN,NaN,NaN

- nunique

In [28]:
# nunique
df.nunique()

Unnamed: 0    50000
ID_code       50000
target            2
var_0          8168
var_1          8157
var_2          8247
var_3             0
var_4          8320
var_5             0
var_6             0
var_7          8328
var_8          6288
var_9             0
var_10            0
var_11            0
var_12            0
var_13            0
var_14         8362
var_15         6374
var_16            0
var_17         8286
var_18            0
var_19            0
var_20         8347
var_21         8270
var_22         8063
var_23            0
var_24         8260
var_25            0
var_26         8148
var_27         8257
var_28         8130
var_29         8156
var_30            0
var_31            0
var_32            0
var_33            0
var_34            0
var_35            0
var_36         7994
var_37         8288
var_38         8277
var_39         8254
var_40            0
var_41         8362
var_42            0
var_43            0
var_44            0
var_45            0
var_46            0
dtype: int64

- unique

In [29]:
# unique
df[target_col].unique()

array([nan,  0.,  1.])

- isnull

In [30]:
# isnull
df.isnull().sum().sort_values( ascending = False )

var_6         50000
var_5         50000
var_11        50000
var_12        50000
var_3         50000
var_13        50000
var_9         50000
var_10        50000
var_42        50000
var_40        50000
var_45        50000
var_46        50000
var_30        50000
var_25        50000
var_23        50000
var_19        50000
var_18        50000
var_16        50000
var_43        50000
var_33        50000
var_44        50000
var_35        50000
var_34        50000
var_31        50000
var_32        50000
var_28        41494
var_0         41494
var_4         41494
var_14        41494
var_7         41494
var_2         41494
var_1         41494
var_8         41494
target        41494
var_15        41494
var_17        41494
var_29        41494
var_26        41494
var_24        41494
var_20        41494
var_21        41494
var_22        41494
var_38        41494
var_37        41494
var_27        41494
var_36        41494
var_41        41494
var_39        41494
Unnamed: 0        0
ID_code           0
dtype: int64

In [31]:
# isnull frequencies
(df.isnull().sum() / df.shape[0]).sort_values( ascending = False ) * 100

var_6         100.000
var_5         100.000
var_11        100.000
var_12        100.000
var_3         100.000
var_13        100.000
var_9         100.000
var_10        100.000
var_42        100.000
var_40        100.000
var_45        100.000
var_46        100.000
var_30        100.000
var_25        100.000
var_23        100.000
var_19        100.000
var_18        100.000
var_16        100.000
var_43        100.000
var_33        100.000
var_44        100.000
var_35        100.000
var_34        100.000
var_31        100.000
var_32        100.000
var_28         82.988
var_0          82.988
var_4          82.988
var_14         82.988
var_7          82.988
var_2          82.988
var_1          82.988
var_8          82.988
target         82.988
var_15         82.988
var_17         82.988
var_29         82.988
var_26         82.988
var_24         82.988
var_20         82.988
var_21         82.988
var_22         82.988
var_38         82.988
var_37         82.988
var_27         82.988
var_36         82.988
var_41         82.988
var_39         82.988
Unnamed: 0      0.000
ID_code         0.000
dtype: float64

- dtypes

In [32]:
# dtypes
df.dtypes

Unnamed: 0      int64
ID_code        object
target        float64
var_0         float64
var_1         float64
var_2         float64
var_3         float64
var_4         float64
var_5         float64
var_6         float64
var_7         float64
var_8         float64
var_9         float64
var_10        float64
var_11        float64
var_12        float64
var_13        float64
var_14        float64
var_15        float64
var_16        float64
var_17        float64
var_18        float64
var_19        float64
var_20        float64
var_21        float64
var_22        float64
var_23        float64
var_24        float64
var_25        float64
var_26        float64
var_27        float64
var_28        float64
var_29        float64
var_30        float64
var_31        float64
var_32        float64
var_33        float64
var_34        float64
var_35        float64
var_36        float64
var_37        float64
var_38        float64
var_39        float64
var_40        float64
var_41        float64
var_42        float64
var_43        float64
var_44        float64
var_45        float64
var_46        float64
dtype: object

In [33]:
# check to see if anything is not zero -- should return 0 if no nulls
df.isnull().sum().sum()

np.int64(2204362)

#### 5. NOTE: the ‘target’ column indicates a successful transaction (‘1’) or a no-transaction (‘0’). Verify these are the only values in that column, and that there are no nulls.

In [34]:
# value counts on target
df[target_col].value_counts( dropna = False )

target
NaN    41494
0.0     7666
1.0      840
Name: count, dtype: int64

In [35]:
# value counts normalized
df[target_col].value_counts( dropna = False, normalize = True ) * 100

target
NaN    82.988
0.0    15.332
1.0     1.680
Name: proportion, dtype: float64

In [36]:
# target col size/shape
df[[target_col]].shape[0]

50000

In [37]:
# sum of nulls in target
df[[target_col]].isnull().sum()

target    41494
dtype: int64

In [41]:
df.isnull().sum()

Unnamed: 0        0
ID_code           0
target        41494
var_0         41494
var_1         41494
var_2         41494
var_3         50000
var_4         41494
var_5         50000
var_6         50000
var_7         41494
var_8         41494
var_9         50000
var_10        50000
var_11        50000
var_12        50000
var_13        50000
var_14        41494
var_15        41494
var_16        50000
var_17        41494
var_18        50000
var_19        50000
var_20        41494
var_21        41494
var_22        41494
var_23        50000
var_24        41494
var_25        50000
var_26        41494
var_27        41494
var_28        41494
var_29        41494
var_30        50000
var_31        50000
var_32        50000
var_33        50000
var_34        50000
var_35        50000
var_36        41494
var_37        41494
var_38        41494
var_39        41494
var_40        50000
var_41        41494
var_42        50000
var_43        50000
var_44        50000
var_45        50000
var_46        50000
dtype: int64

In [53]:
df.isnull().sum()[df.isnull().sum() != 50000]

Unnamed: 0        0
ID_code           0
target        41494
var_0         41494
var_1         41494
var_2         41494
var_4         41494
var_7         41494
var_8         41494
var_14        41494
var_15        41494
var_17        41494
var_20        41494
var_21        41494
var_22        41494
var_24        41494
var_26        41494
var_27        41494
var_28        41494
var_29        41494
var_36        41494
var_37        41494
var_38        41494
var_39        41494
var_41        41494
dtype: int64

- Summary:

  - target column: 'target'
  - feature columns: 'var_0' - 'var_11'
  - identifier columns (likely): 'Unnamed', 'ID_code'
  - null columns: 6 [3, 6, 11, 9, 10, 5]
  - null rows (target): 8314

#### 6. If there are data cleaning issues, develop recommendations for how to deal with them.  Specifically, handle these common issues:

    - identifer columns
    - target column with null counts
    - feature columns with high null counts
    - feature columns with low null counts
    - feature columns with medium null counts

In [ ]:
# head again to double-check
df.head()

In [ ]:
# 1. 'Unnamed' and 'ID_code are very likely identifier columns, and should be dropped; target and var_0 - var_11 will be kept
# 2. 8314 null target columns should be dropped
# 3. 6 null feature columns should be dropped
# 4. After this, drop rows for any column with low null count
# 5. Finally, impute remaining nulls with column medians

- backup 1

In [ ]:
# make backup
df_bak = df.copy()
df_bak

In [ ]:
# restore from backup
df = df_bak.copy()
df

In [ ]:
# keep the target and all features
df = df.drop( columns = ['Unnamed: 0', 'ID_code'] )

In [ ]:
# check our dataframe (display transformed df)
df

- backup 2

In [ ]:
# backup 2
df_bak2 = df.copy()
df_bak2

In [ ]:
# restore from backup 2
df = df_bak2.copy()
df

In [ ]:
# preview filtering rows for where target is null
df.loc[df[target_col].isnull() == False]

In [ ]:
# execute the drop
df = df.loc[df[target_col].isnull() == False].copy()
df

In [ ]:
# backup 3
df_bak3 = df.copy()
df_bak3

In [ ]:
# restore from backup
df = df_bak3.copy()
df

In [ ]:
# preview drop null columns
df.drop( columns = ['var_3', 'var_5', 'var_6', 'var_9', 'var_10', 'var_11'] )

In [ ]:
# drop columns
df = df.drop( columns = ['var_3', 'var_5', 'var_6', 'var_9', 'var_10', 'var_11'] )
df

In [ ]:
# make a backup
df_bak4 = df.copy()
df_bak4

In [ ]:
# restore from backup
df = df_bak4.copy()
df

In [ ]:
# look for nulls in new cleaned data frame
df.isnull().sum().sort_values( ascending = False )

In [ ]:
# No more null values, so we're done! ( skip numbers 4 and 5 from above :D )

## Exploratory Data Analysis

Produce some visual analysis of the data.  Recall that Gaussian Naive Bayes assumes the features are normally distributed and independent. Note: you might have to do multiple plots in groups.

#### 7. Check the distributions of all variables by plotting.

In [ ]:
# Display a histogram
df.hist(figsize=(10, 10))

In [ ]:
# display a boxplot
df.boxplot(figsize=(10, 10))

#### 8. Check the correlation values between all **feature columns** to ensure there are no substantial correlations between features. This is important to support the decision to classify the ‘target’ using Naïve Bayes.

In [ ]:
# column correlations
column_correlations = df.corr()
column_correlations

In [ ]:
# Display correlation matrix
plt.figure(figsize = (10, 10))
sns.heatmap(
    column_correlations,
    annot = True,
    vmin = -1,
    vmax = 1,
    cmap = 'RdYlGn'
)

#### 9. Create two data frames: one with all successful transactions, one with all unsuccessful transactions. **Make sure they are copies and not slices**.

In [ ]:
# make successful (copy)
df_successful   = df[ df[target_col] == 1 ].copy()
df_successful

In [ ]:
# make unsuccessful (copy)
df_unsuccessful = df[ df[target_col] == 0 ].copy()
df_unsuccessful

## Data Processing

### Single Cross-validation ( CV )

#### 10. Create two data sets: one with all the feature columns (everything except for Unnamed: 0, ID_code and target) and one with just the target. Make sure they are copies and not slices.  And make sure they are the correct dimensions.

In [ ]:
# make target and features
target   = df[ target_col ].copy()
features = df.drop( columns = [target_col] ).copy()

In [ ]:
# check target
target

In [ ]:
# check target value counts
target.value_counts()

In [ ]:
# check target dimensions and type
type(target), target.shape, target.ndim

In [ ]:
# check features
features

In [ ]:
# check features dimensions and type
type(features), features.shape, features.ndim

#### 11. Define an empty Gaussian Naïve Bayes model using Sklearn.

In [ ]:
# Create an empty GNB model
modelGNB = GaussianNB()

#### 12. Divide the two data sets you created in step #10 into training and testing subsets, i.e. train-test split.

In [ ]:
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split( features, target, test_size = 0.25 )

#### 13. Train ( fit ) the model using the training subset of the dataset.

In [ ]:
# Train ( fit ) the model
modelGNB.fit(X_train, y_train)

#### 14. Test the model ( predict ) using the testing subset of the dataset.

In [ ]:
# Make predictions using the model
y_pred = modelGNB.predict(X_test)

#### 15. Calculate and report the accuracy.

In [ ]:
# Calculate the accuracy
accuracy = metrics.accuracy_score(y_test, y_pred)
accuracy

#### 16. Present a confusion matrix and heatmap

In [ ]:
# Display confusion matrix
matrix = metrics.confusion_matrix(y_test, y_pred)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

#### 17. Present the results of a Classification Report (sklearn.metrics.classification_report).

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test, y_pred, output_dict = True, zero_division = 0)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

In [ ]:
# Save variable values
X_train_SCV = X_train
X_test_SCV  = X_test
y_train_SCV = y_train
y_test_SCV  = y_test
y_pred_SCV  = y_pred



### Multiple Cross-validation ( CV )

#### 18. Perform a cross-validation loop and record the accuracy of your model during each iteration.

In [ ]:
loop_count = 100

In [ ]:
# Multiple CV loop

# Create array to hold results (accuracies)
n = loop_count
accuracies = np.zeros(n)

# Multiple CV loop
for i in range(n):

  # Train Test Split
  X_train, X_test, y_train, y_test = train_test_split( features, target, test_size = 0.25 )

  # Create an empty GNB model
  modelGNB = GaussianNB()

  # Train ( fit ) the model
  modelGNB.fit(X_train, y_train)

  # Make predictions using the model
  y_pred = modelGNB.predict(X_test)

  # Calculate the accuracy and save to array
  accuracies[i] = metrics.accuracy_score(y_test, y_pred)

#### 19. Report the mean accuracy. How does it compare to the accuracy you calculated for the Single CV?

In [ ]:
# Calculate mean of results (mean accuracy)
mean_accuracy = accuracies.mean()
mean_accuracy

In [ ]:
# Save variable values
X_train_MCV = X_train
X_test_MCV  = X_test
y_train_MCV = y_train
y_test_MCV  = y_test
y_pred_MCV  = y_pred

Analysis:

- Multiple Cross Validation (Multiple CV) gives a mean accuracy of 91.1% at 100 iterations and 91.1233% at 1000 iterations (so 91.1%).
- This is about the same as the result calculated for the Single CV, which in the previous pass was 91.2%.

#### 20. Plot a histogram of the accuracy scores you generated in your cross-validation loop. What do you notice about the distribution of accuracy scores?

In [ ]:
# Display a histogram of the results
pd.Series(accuracies).hist(bins = 30)

In [ ]:
# --> The distribution of accuracy scores mostly follows a normal distribution.

#### 21. Present a confusion matrix and heatmap

In [ ]:
# Display a confusion matrix of final result of y_test and y_pred
matrix = metrics.confusion_matrix(y_test, y_pred)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

#### 22. Present the results of a Classification Report (sklearn.metrics.classification_report). What do you notice? That is, how do the different metrics compare to each other?

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test, y_pred, output_dict = True)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

Analysis:

- The precision of the model is good for negatives (no transaction) — around 92% — but relatively poor when predicting positives (successful transactions), hovering around 66%. These results worsen when looking at recall (true positives accuracy), which is 98.7% accurate for negatives but only 22.1% accurate for positives. The f1 scores for negatives is similarly high, around 95.2%, and for positives is lower again, at 33.7%.


### Balanced data set

The training data is very skewed towards non-successful transactions (about 90% of the training data has ‘target’==0).

#### 23. Remove enough non-successful transaction rows so that your remaining training data is 50%/50% split between successful and non-successful transactions. Hint: you can use the data frames you created in step #9.

In [ ]:
# review value counts
df[target_col].value_counts()

In [ ]:
# review head of successful
df_successful.head()

In [ ]:
# review head of unsuccessful
df_unsuccessful.head()

- df_unsuccessful is the majority class. Therefore, we can undersample our unsuccessful dataframe as follows:

In [ ]:
# preview output of undersampling (downsampling)
df_unsuccessful.sample(df_successful.shape[0]).head()

In [ ]:
# downsample
df_unsuccessful = df_unsuccessful.sample(df_successful.shape[0])

In [ ]:
# check it
df_unsuccessful.head()

In [ ]:
# check sizes to ensure they match
df_successful.shape[0], df_unsuccessful.shape[0]

In [ ]:
# Combine data frames
df = pd.concat([df_unsuccessful, df_successful], ignore_index = True)
df

In [ ]:
# check value counts to make sure target successful and unsuccessful counts are equal
df[target_col].value_counts()

In [ ]:
# make a backup
df_bak3 = df.copy()
df_bak3

In [ ]:
df = df_bak3.copy()
df

In [ ]:
# make target and features again
target   = df[ target_col ].copy()
features = df.drop( columns = [target_col] ).copy()

In [ ]:
target

In [ ]:
type(target), target.shape, target.ndim

In [ ]:
features

In [ ]:
type(features), features.shape, features.ndim

#### 24. Repeat the multiple cross-validation process on this data set.

In [ ]:
loop_count = 100 # reset the loop count for this loop

In [ ]:
# Multiple CV loop

# Create array to hold results (accuracies)
n = loop_count
accuracies_balanced = np.zeros(n)

# Multiple CV loop
for i in range(n):

  # Train Test Split
  X_train, X_test, y_train, y_test = train_test_split( features, target, test_size = 0.25 )

  # Create an empty GNB model
  modelGNB = GaussianNB()

  # Train ( fit ) the model
  modelGNB.fit(X_train, y_train)

  # Make predictions using the model
  y_pred = modelGNB.predict(X_test)

  # Calculate the accuracy and save to array
  accuracies_balanced[i] = metrics.accuracy_score(y_test, y_pred)

#### 25. Report what your mean accuracy for this balanced data set.

In [ ]:
# Calculate mean of results
mean_accuracy_balanced = accuracies_balanced.mean()
mean_accuracy_balanced

In [ ]:
# Save variable values
X_train_BAL = X_train
X_test_BAL  = X_test
y_train_BAL = y_train
y_test_BAL  = y_test
y_pred_BAL  = y_pred

#### 26. Plot a histogram of the accuracy scores you generated in your cross-validation loop. What do you notice about the distribution of accuracy scores?

In [ ]:
# Display a histogram of the results
pd.Series(accuracies_balanced).hist(bins = 30)

#### 27. Present a confusion matrix and heatmap

In [ ]:
# Display a confusion matrix of final result of y_test and y_pred
matrix = metrics.confusion_matrix(y_test, y_pred)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

#### 28. Present the results of a Classification Report (sklearn.metrics.classification_report). What do you notice? That is, how do the different metrics compare to each other?

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test, y_pred, output_dict = True)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

## Data Visualization

#### 29. Compare the accuracy results of your multiple cross-validation with the whole training data and the balanced training data

In [ ]:
accuracy

In [ ]:
float(mean_accuracy)

In [ ]:
float(mean_accuracy_balanced)

#### 30. Present the confusion matrix and heatmap

In [ ]:
# Display a confusion matrix of final result of y_test and y_pred
matrix = metrics.confusion_matrix(y_test_SCV, y_pred_SCV)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

In [ ]:
# Display a confusion matrix of final result of y_test and y_pred
matrix = metrics.confusion_matrix(y_test_MCV, y_pred_MCV)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

In [ ]:
# Display a confusion matrix of final result of y_test and y_pred
matrix = metrics.confusion_matrix(y_test_BAL, y_pred_BAL)
sns.heatmap(
    matrix.T,
    square = True,
    annot = True,
    fmt = 'd',
    cbar = False
)
plt.xlabel('Actual')
plt.ylabel('Predicted')

#### 31. Present the results of your Classification Report (sklearn.metrics.classification_report)

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test_SCV, y_pred_SCV, output_dict = True)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test_MCV, y_pred_MCV, output_dict = True)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

In [ ]:
# 1. Generate the report (as a dictionary, for formatting)
report = metrics.classification_report(y_test_BAL, y_pred_BAL, output_dict = True)

# 2. Convert to DataFrame and transpose
df_report = pd.DataFrame(report).T
df_report

## Communicate the Results

#### 32. Communicate the results of your analysis.

Conclusions (Brief):

- The mean accuracy for the balanced set was considerably lower than the accuracy and mean accuracy for the SingleCV and MultipleCV sets, at around 75%.
- The precision of true negatives likewise decreased from around 91% to 75%.
- However, the accuracy of prediction for true negatives has gone up, from around 66% to 75%.
- Even more significant, the recall of positives (ratio of true positives to total positives) has gone way up, from 22% to 75%.
- Percentage accuracy, recall, and f1-score of false positives, false negatives, true positives, and true negatives all about the same as each other.
- Much more balanced (and informative) model.

Future Work:
- bigger data set
- other types of validation?
- other types of data set balancing (upsampling?)
- different model

## Submit Final Project

#### 33. Save ( commit ) your finished Jupyter notebook to your Project 1 GitHub repo.